services:
  genesis:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    volumes:
      - ./data:/app/data
    env_file: .env
    ports:
      - "${PORT:-8000}:8000"
    restart: unless-stopped
    # Optional healthcheck once API is up
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 6
