name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: abatilo/actions-poetry@v3
      - name: Install deps
        run: |
          poetry install --no-root
      - name: Lint
        run: |
          poetry run ruff .
      - name: Test
        run: |
          poetry run pytest -q
